### ISSUE TITLE
Shitty license

### ISSUE THREAD

**Issue by tomalbrc** [Forty-Bot/100Base-X#1]
The AGPL license prevents me and many others from using this.

**Comment by YousufSSyed** [comment]
I assumed u wrote this after reading this post from marcan42?! 😂😂😂 https://social.treehouse.systems/@marcan/110038008055623292

**Comment by Patronics** [comment]
It's worth noting that the readme doesn't mention this change in licensing, so you may want to consider adjusting that too :)
